name: Build develop

on:
  push:
    branches: 
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build package project
      run: |
        nuget restore
        msbuild EventAggregatorMocker/EventAggregatorMocker.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release

  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Android example
      run: |
        cd EventAggregator_Mocker/Examples/Xamarin.Forms/
        nuget restore
        cd EventAggregatorTest.Android
        msbuild EventAggregatorTest.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build iOS example
      run: |
        cd EventAggregator_Mocker/Examples/Xamarin.Forms/
        nuget restore
        msbuild EventAggregatorTest.iOS/EventAggregatorTest.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
