name: Build master

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build package project
      run: |
        nuget restore
        msbuild EventAggregatorMocker/EventAggregatorMocker.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
        