name: Build and deploy

on:
  push:
    branches: 
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build EventAggregatorMocker/EventAggregatorMocker.csproj --configuration Release --no-restore --verbosity normal
    - name: publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: EventAggregatorMocker/EventAggregatorMocker.csproj
        VERSION_REGEX: <ReleaseVersion>(.*)<\/ReleaseVersion>
        NUGET_KEY: NUGET_API_KEY